import { describe, it, expect } from "vitest";
import { looksAutoGenerated } from "@/lib/trackName";

/**
 * This is the client-side mirror of the server's naming rules — it exists to
 * flag "8432.mp3" while the user is still typing, before a round trip. The
 * server (backend/src/upload/nameValidation.ts) stays the authority, so the
 * client is allowed to be more permissive, but it must never be *stricter*:
 * a false positive here disables the Next button on a legitimate title.
 */
describe("looksAutoGenerated — flags machine names", () => {
  it.each([
    "8432",
    "8432.mp3",
    "song.wav",
    "track_01",
    "untitled",
    "New Recording",
    "recording",
    "audio",
    "1234567",
    "01 - 02",
    "aaaaaaa",
    "kjhdfg",
    "۱۲۳۴",
  ])("flags %j", (value) => {
    expect(looksAutoGenerated(value)).toBe(true);
  });
});

describe("looksAutoGenerated — leaves real names alone", () => {
  it.each([
    "Seyl",
    "سیل",
    "Seyl (سیل)",
    "Bohemian Rhapsody",
    "24K Magic",
    "7 Rings",
    "M.I.A",
    "شب‌های تهران",
    "دلتنگی",
    "Man o To",
    "Numb",
    "Concrete Flow",
    "Midnight Drive",
  ])("accepts %j", (value) => {
    expect(looksAutoGenerated(value)).toBe(false);
  });
});

describe("looksAutoGenerated — while typing", () => {
  it("stays quiet on a partial entry, so the field doesn't shout mid-word", () => {
    expect(looksAutoGenerated("")).toBe(false);
    expect(looksAutoGenerated("S")).toBe(false);
  });

  it("ignores surrounding whitespace", () => {
    expect(looksAutoGenerated("   Seyl   ")).toBe(false);
    expect(looksAutoGenerated("  8432  ")).toBe(true);
  });
});
