/**
 * Client-side mirror of the server's naming rules — just enough to catch the
 * obvious cases while the user is still typing. The server remains the
 * authority (see backend/src/upload/nameValidation.ts); this only exists so
 * "8432.mp3" is flagged before a round trip.
 */

const FILE_EXTENSION = /\.(mp3|wav|m4a|aac|flac|ogg|opus|wma|mp4|tmp)\s*$/i;
const MACHINE = /^(track|song|audio|music|file|untitled|unknown|new recording|recording|aud|rec|img|vid)[\s_-]*\d*$/i;
const LATIN_VOWEL = /[aeiouy]/i;

/** True when a name is clearly a file name or placeholder rather than a title. */
export function looksAutoGenerated(raw: string): boolean {
  const value = raw.trim().replace(/\s+/g, " ");
  if (value.length < 2) return false; // too early to complain
  if (FILE_EXTENSION.test(value)) return true;
  if (MACHINE.test(value)) return true;

  const letters = value.replace(/[^\p{L}]/gu, "");
  const digits = value.replace(/[^\p{N}]/gu, "");
  if (letters.length < 2) return true; // "8432", "01 - 02"
  if (digits.length > letters.length) return true;
  if (/(.)\1{4,}/u.test(value)) return true;

  const hasPersian = /[؀-ۿ]/.test(value);
  if (!hasPersian && /^[A-Za-z\s]+$/.test(value) && letters.length >= 4 && !LATIN_VOWEL.test(letters)) {
    return true;
  }
  return false;
}
